-- PL/SQL 
--문제1) EMPLOYEES 테이블에 등록된 총사원의 수와 급여의 평균을 변수에 대입하여 출력(변수 대입 INTO)

DECLARE
    TOTAL_EMPLOYEE NUMBER(4);
    TOTAL_SALARY NUMBER(10);
    AVG_SALARY NUMBER(10);
BEGIN
   SELECT COUNT(EMPLOYEE_ID), SUM(SALARY), ROUND(AVG(SALARY))
   INTO TOTAL_EMPLOYEE,TOTAL_SALARY,AVG_SALARY
   FROM EMPLOYEES;

   DBMS_OUTPUT.PUT_LINE('총사원의 수: '||TOTAL_EMPLOYEE);
   DBMS_OUTPUT.PUT_LINE('급여의 합: '||TOTAL_SALARY);
   DBMS_OUTPUT.PUT_LINE('급여의 평균: '||AVG_SALARY);
END;
/
SELECT COUNT(*), SUM(SALARY), ROUND(AVG(SALARY)) FROM EMPLOYEES; --COUNT를 사용하면 전체가 GROUP BY가 된다
--SELECT DEPARTMENT_ID, COUNT(*), SUM(SALARY), ROUND(AVG(SALARY)) FROM EMPLOYEES GROUP BY DEPARTMENT_ID;

-- PL/SQL 
-- FOR IN LOOP 구구단 작성하기
DECLARE
    I NUMBER(2);
BEGIN
    DBMS_OUTPUT.PUT_LINE('구구단');
    DBMS_OUTPUT.PUT_LINE('------------------');
    FOR I IN 1..9 LOOP
        FOR J IN 1..9 LOOP
            DBMS_OUTPUT.PUT_LINE( I || ' X ' || J || ' = ' || I*J);
        END LOOP;
        DBMS_OUTPUT.PUT_LINE('------------------');
    END LOOP;
END;
/
