--순위함수 RANK(), DENSE_RANK, ROWNUM
--ROWNUM 구하는 순위(공동순위는 없다)/게시판, 공지사항, 장바구니, 자료실 .. 등등 사용
DROP TABLE EMP02;
CREATE TABLE EMP02 
AS
SELECT * FROM EMPLOYEES WHERE 1 = 1; --구조 내용 모두 복사
SELECT * FROM EMPLOYEES;
SELECT ROWNUM, FIRST_NAME, SALARY FROM EMPLOYEES ORDER BY SALARY DESC;
SELECT ROWNUM, FIRST_NAME, SALARY FROM EMPLOYEES;
SELECT ROWNUM, FIRST_NAME, SALARY FROM (SELECT FIRST_NAME, SALARY FROM EMPLOYEES ORDER BY SALARY DESC);

--공동순위를 구하는 방법 RANK(), DENSE_RANK()
--RANK()
SELECT RANK() OVER(ORDER BY SALARY DESC) AS RANK ,FIRST_NAME, SALARY FROM EMPLOYEES ORDER BY SALARY DESC;

SELECT ROWNUM, RANK() OVER(ORDER BY SALARY DESC) AS RANK ,FIRST_NAME, SALARY 
FROM (SELECT FIRST_NAME, SALARY FROM EMPLOYEES ORDER BY SALARY DESC) ORDER BY SALARY DESC;
--DENSE_RANK()
SELECT ROWNUM, DENSE_RANK() OVER(ORDER BY SALARY DESC) AS DENSE_RANK ,FIRST_NAME, SALARY 
FROM EMPLOYEES ORDER BY SALARY DESC;

SELECT ROWNUM, DENSE_RANK() OVER(ORDER BY SALARY DESC) AS DENSE_RANK ,FIRST_NAME, SALARY 
FROM (SELECT FIRST_NAME, SALARY FROM EMPLOYEES ORDER BY SALARY DESC) ORDER BY SALARY DESC;
--RANK+DENSE
SELECT ROWNUM, RANK() OVER(ORDER BY SALARY DESC) AS RANK, DENSE_RANK() OVER(ORDER BY SALARY DESC) AS DENSE_RANK ,FIRST_NAME, SALARY 
FROM (SELECT FIRST_NAME, SALARY FROM EMPLOYEES ORDER BY SALARY DESC) ORDER BY SALARY DESC;

-- 중복순위를 없애기
SELECT RANK() OVER(ORDER BY SALARY DESC, COMMISSION_PCT DESC, DEPARTMENT_ID DESC) AS RANK,
FIRST_NAME, SALARY, COMMISSION_PCT, DEPARTMENT_ID
FROM EMPLOYEES ORDER BY SALARY DESC;

--부서별 순위 구하기
SELECT DEPARTMENT_ID, RANK() OVER(PARTITION BY DEPARTMENT_ID ORDER BY SALARY DESC, COMMISSION_PCT DESC, DEPARTMENT_ID DESC) AS RANK,
FIRST_NAME, SALARY, COMMISSION_PCT
FROM EMPLOYEES ORDER BY DEPARTMENT_ID, SALARY DESC, COMMISSION_PCT DESC;

--ROWNUM 규칙 중요(조심)
--2PAGE
--START := ((NUM_PAGE_NO-1) * NUM_PAGE_SIZE) + 1 # 출력페이지 시작 행 
--END := (NUM_PAGE_NO * NUM_PAGE_SIZE)  # 출력페이지 마지막 행 

SELECT ROWNUM , E.* FROM EMPLOYEES E  WHERE ROWNUM BETWEEN 11 AND 20;
SELECT ROWNUM, E.* FROM EMPLOYEES E;
--순위 구하는 방법 (비추)
SELECT RNUM, FIRST_NAME, SALARY, DEPARTMENT_ID  FROM (SELECT ROWNUM AS RNUM, E.*FROM EMPLOYEES E)
WHERE RNUM BETWEEN 100 AND 110;

--순위 구하는 방법 (강추)/속도가 훨씬 빠름
SELECT RNUM, FIRST_NAME, SALARY, DEPARTMENT_ID  FROM (SELECT ROWNUM AS RNUM, E.*FROM EMPLOYEES E WHERE ROWNUM <=110)
WHERE RNUM >= 100;
