-- PL/SQL 
--문제1) EMPLOYEES 테이블에 등록된 총사원의 수와 급여의 평균을 변수에 대입하여 출력(변수 대입 INTO)

DECLARE
    TOTAL_EMPLOYEE NUMBER(4);
    TOTAL_SALARY NUMBER(10);
    AVG_SALARY NUMBER(10);
BEGIN
   SELECT COUNT(EMPLOYEE_ID), SUM(SALARY), ROUND(AVG(SALARY))
   INTO TOTAL_EMPLOYEE,TOTAL_SALARY,AVG_SALARY
   FROM EMPLOYEES;

   DBMS_OUTPUT.PUT_LINE('총사원의 수: '||TOTAL_EMPLOYEE);
   DBMS_OUTPUT.PUT_LINE('급여의 합: '||TOTAL_SALARY);
   DBMS_OUTPUT.PUT_LINE('급여의 평균: '||AVG_SALARY);
END;
/
SELECT COUNT(*), SUM(SALARY), ROUND(AVG(SALARY)) FROM EMPLOYEES; --COUNT를 사용하면 전체가 GROUP BY가 된다
--SELECT DEPARTMENT_ID, COUNT(*), SUM(SALARY), ROUND(AVG(SALARY)) FROM EMPLOYEES GROUP BY DEPARTMENT_ID;

-- PL/SQL 
-- DEPARTMENTS 테이블에 전체내용을 COUSOR 저장하고 FETCH해서 전체 정보를 출력하시오.
DECLARE
    VDEP DEPARTMENTS%ROWTYPE;
    --CURSOR C1 IS SELECT * FROM DEPARTMENTS;
BEGIN

    FOR VDEP IN (SELECT * FROM DEPARTMENTS) LOOP
        DBMS_OUTPUT.PUT_LINE(VDEP.DEPARTMENT_ID || ' / ' || VDEP.DEPARTMENT_NAME);
    END LOOP; --CURSOR를 향상된 FOR문으로 했을 때
    /************************************
    OPEN C1;
    LOOP
        FETCH C1 INTO VDEP.DEPARTMENT_ID, VDEP.DEPARTMENT_NAME, VDEP.MANAGER_ID,VDEP.LOCATION_ID;
        EXIT WHEN C1%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE(VDEP.DEPARTMENT_ID || ' / ' || VDEP.DEPARTMENT_NAME);
    END LOOP;
    CLOSE C1;
        *********************************/
END;
/


