-- PL/SQL 
--문제1) EMPLOYEES 테이블에 등록된 총사원의 수와 급여의 평균을 변수에 대입하여 출력(변수 대입 INTO)

DECLARE
    TOTAL_EMPLOYEE NUMBER(4);
    TOTAL_SALARY NUMBER(10);
    AVG_SALARY NUMBER(10);
BEGIN
   SELECT COUNT(EMPLOYEE_ID), SUM(SALARY), ROUND(AVG(SALARY))
   INTO TOTAL_EMPLOYEE,TOTAL_SALARY,AVG_SALARY
   FROM EMPLOYEES;

   DBMS_OUTPUT.PUT_LINE('총사원의 수: '||TOTAL_EMPLOYEE);
   DBMS_OUTPUT.PUT_LINE('급여의 합: '||TOTAL_SALARY);
   DBMS_OUTPUT.PUT_LINE('급여의 평균: '||AVG_SALARY);
END;
/
SELECT COUNT(*), SUM(SALARY), ROUND(AVG(SALARY)) FROM EMPLOYEES; --COUNT를 사용하면 전체가 GROUP BY가 된다
--SELECT DEPARTMENT_ID, COUNT(*), SUM(SALARY), ROUND(AVG(SALARY)) FROM EMPLOYEES GROUP BY DEPARTMENT_ID;


--문제2)Clara 사원의 직무, 급여, 입사일자, 커미션, 부서명을 변수에 대입하여 출력
DECLARE
--레코드 변수 선언
EMP_RECORD EMPLOYEES%ROWTYPE;
BEGIN
--CLARA 사원의 정보
SELECT * INTO EMP_RECORD
FROM EMPLOYEES
WHERE FIRST_NAME = 'Clara';
--레코드 변수에 저장된 사원 정보 출력
DBMS_OUTPUT.PUT_LINE('이름 :'||EMP_RECORD.FIRST_NAME);
DBMS_OUTPUT.PUT_LINE('직무 :'||EMP_RECORD.JOB_ID);
DBMS_OUTPUT.PUT_LINE('급여 :'||EMP_RECORD.SALARY);
DBMS_OUTPUT.PUT_LINE('입사일자 :'||TO_CHAR(EMP_RECORD.HIRE_DATE,'YYYY-MM-DD'));
DBMS_OUTPUT.PUT_LINE('커미션 :'||EMP_RECORD.COMMISSION_PCT);
DBMS_OUTPUT.PUT_LINE('부서명 :'||EMP_RECORD.DEPARTMENT_ID);
END;
/

-------------------
SELECT JOB_ID, SALARY, HIRE_DATE, COMMISSION_PCT, DEPARTMENT_ID FROM EMPLOYEES WHERE FIRST_NAME ='Clara';
SELECT DEPARTMENT_NAME, DEPARTMENT_ID FROM DEPARTMENTS;

SELECT JOB_ID, SALARY, HIRE_DATE, COMMISSION_PCT, DEPARTMENT_NAME 
FROM EMPLOYEES E INNER JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID WHERE FIRST_NAME ='Clara';

DECLARE
    VFIRST_NAME EMPLOYEES.FIRST_NAME%TYPE;
    VJOB_ID EMPLOYEES.JOB_ID%TYPE;
    VSALARY EMPLOYEES.SALARY%TYPE;
    VHIRE_DATE EMPLOYEES.HIRE_DATE%TYPE;
    VCOMMISSION_PCT EMPLOYEES.COMMISSION_PCT%TYPE;
    VDEPARTMENT_NAME DEPARTMENTS.DEPARTMENT_NAME%TYPE;
BEGIN
    SELECT FIRST_NAME, JOB_ID, SALARY, HIRE_DATE, COMMISSION_PCT, DEPARTMENT_NAME
    INTO VFIRST_NAME, VJOB_ID, VSALARY, VHIRE_DATE, VCOMMISSION_PCT, VDEPARTMENT_NAME
    FROM EMPLOYEES E INNER JOIN DEPARTMENTS D ON e.department_id=d.department_id
    WHERE FIRST_NAME = 'Clara';

    DBMS_OUTPUT.PUT_LINE('이름 : '||VFIRST_NAME);
    DBMS_OUTPUT.PUT_LINE('직무 : '||VJOB_ID);
    DBMS_OUTPUT.PUT_LINE('급여 : '||VSALARY);
    DBMS_OUTPUT.PUT_LINE('입사일자 : '||VHIRE_DATE);
    DBMS_OUTPUT.PUT_LINE('커미션 : '||VCOMMISSION_PCT);
    DBMS_OUTPUT.PUT_LINE('부서명 : '||VDEPARTMENT_NAME);
END;
/

