 CREATE table CUSTOMER (
 ID VARCHAR2(12),
 PWD VARCHAR2(12) NOT NULL,
 NAME VARCHAR2(30) NOT NULL,
 NICKNAME VARCHAR2(10) NOT NULL,
 EMAIL VARCHAR2(30) NOT NULL,
 TEL VARCHAR2(14) NOT NULL,
 PHONE VARCHAR2(14) NOT NULL,
 BIRTH VARCHAR2(30),
 ZIPCODE VARCHAR2(7) NOT NULL,
 ADDRESS1 VARCHAR2(120) NOT NULL,
 ADDRESS2 VARCHAR2(50)
);
ALTER TABLE CUSTOMER ADD CONSTRAINT CUSTOMER_ID_PK PRIMARY KEY(ID);

create table zipcode (
 seq NUMBER(10) not null,
 zipcode VARCHAR2(50),
 sido VARCHAR2(50),
 gugun VARCHAR2(50),
 dong VARCHAR2(50),
 bunji VARCHAR2(100)
);

ALTER TABLE zipcode ADD CONSTRAINT zipcode_SEQ_PK PRIMARY KEY(SEQ);

CREATE TABLE notice(
NO NUMBER(8),--pk
TITLE VARCHAR2(100) NOT NULL,
CONTENT VARCHAR2(4000) NOT NULL,
COUNT NUMBER(5) DEFAULT 0,
SUBDATE DATE NOT NULL
);
ALTER TABLE NOTICE ADD CONSTRAINT NOTICE_NO_PK PRIMARY KEY(NO);
create or replace view notice_rnum as 
select rownum as rnum, no, title, content, count,subdate from (select * from notice order by subdate) order by rnum;

CREATE TABLE board(
NO NUMBER(8),--pk
CUSTOMER_ID VARCHAR2(12),--FK
TITLE VARCHAR2(100) NOT NULL,
CONTENT VARCHAR2(4000) NOT NULL,
COUNT NUMBER(5) DEFAULT 0,
SUBDATE DATE NOT NULL
);
ALTER TABLE BOARD ADD CONSTRAINT BOARD_NO_PK PRIMARY KEY(NO);
ALTER TABLE BOARD ADD CONSTRAINT BOARD_CUSTOMER_ID_FK FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER(ID);


create or replace view BOARD_J_CUSTOMER_ROWNUM AS
SELECT ROWNUM AS RNUM, NO, NAME, CUSTOMER_ID,TITLE,CONTENT,COUNT,SUBDATE  FROM BOARD_J_CUSTOMER;
CREATE OR REPLACE  VIEW "WEBUSER"."BOARD_J_CUSTOMER" AS 
SELECT B.NO,C.NAME,CUSTOMER_ID, B.TITLE,B.CONTENT, B.COUNT,B.SUBDATE  FROM BOARD B LEFT JOIN CUSTOMER C ON B.CUSTOMER_ID=C.ID ORDER BY B.no;
  
  
CREATE TABLE B_COMMENT(
NO	NUMBER(10),
CUSTOMER_ID VARCHAR2(12),   --FK
BOARD_NO	NUMBER(8),      --FK
PARENT_NO	NUMBER(10),     --재귀
DEPTH NUMBER(2),            --단계표시
CONTENT	VARCHAR2(500),
SUBDATE DATE
);
ALTER TABLE B_COMMENT ADD CONSTRAINT B_COMMENT_NO_PK PRIMARY KEY(NO);
ALTER TABLE B_COMMENT ADD CONSTRAINT B_COMMENT_CUSTOMER_ID_FK FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER(ID) on delete cascade;
ALTER TABLE B_COMMENT ADD CONSTRAINT B_COMMENT_BOARD_NO_FK FOREIGN KEY(BOARD_NO) REFERENCES BOARD(NO) on delete cascade;
--댓글 계층구조로 조회. 쿼리문에 사용예정
SELECT LEVEL, NO, BOARD_NO, CUSTOMER_ID, PARENT_NO, content, DEPTH, SUBDATE FROM B_COMMENT START WITH parent_NO=0 CONNECT BY PRIOR NO = parent_NO ORDER SIBLINGS BY SUBDATE ASC;


CREATE TABLE PRODUCT(
NO NUMBER(10),
NAME VARCHAR2(30),   
PRICE	NUMBER(8),      
AMOUNT	NUMBER(10),    
SUBDATE DATE
);
ALTER TABLE PRODUCT ADD CONSTRAINT PRODUCT_NO_PK PRIMARY KEY(NO);
create or replace view product_rnum as
select ROWNUM AS RNUM, NO , NAME, PRICE,AMOUNT,SUBDATE FROM (SELECT * FROM PRODUCT ORDER BY SUBDATE);

CREATE TABLE SHOP(
NO NUMBER(10),
TYPE NUMBER(1),
PRODUCT_NO NUMBER(10), --FK
TITLE VARCHAR2(30),   
CONTENT	VARCHAR2(1000),     
SUBDATE DATE
);
ALTER TABLE SHOP ADD CONSTRAINT SHOP_NO_PK PRIMARY KEY(NO);
ALTER TABLE SHOP ADD CONSTRAINT SHOP_PRODUCT_NO_FK FOREIGN KEY(PRODUCT_NO) REFERENCES PRODUCT(NO) ON DELETE CASCADE;
SELECT * FROM (SELECT * FROM SHOP_RNUM ORDER BY NO DESC);

create or replace view SHOP_RNUM AS
SELECT ROWNUM AS RNUM , s.NO ,s.type,s.PRODUCT_NO,p.name,p.price,p.amount,s.TITLE,s.CONTENT,url as titleurl,s.SUBDATE FROM SHOP s left join
product p
on s.product_no=p.no
left join
(select url,shop_no from SHOP_IMG where type='TITLE') i
on s.no=i.shop_no
ORDER BY S.SUBDATE;

CREATE TABLE SHOP_IMG(
NO NUMBER(10),
TYPE VARCHAR2(10) CHECK (type IN ('TITLE', 'CONTENT')),
SHOP_NO NUMBER(10),
URL VARCHAR2(1000) 
);
ALTER TABLE SHOP_IMG DROP CONSTRAINT SHOP_IMG_SHOP_NO_FK;
ALTER TABLE SHOP_IMG ADD CONSTRAINT SHOP_IMG_NO_PK PRIMARY KEY(NO);
ALTER TABLE SHOP_IMG ADD CONSTRAINT SHOP_IMG_SHOP_NO_FK FOREIGN KEY(SHOP_NO) REFERENCES SHOP(NO) ON DELETE CASCADE;
 
